workflows:
  android-apk:
    name: Android APK

    environment:
      vars:
        PACKAGE_NAME: "com.btc.bot"
      node: latest

    scripts:
      - npm install
      - npm install -g eas-cli
      - eas build --platform android --profile preview --non-interactive

    artifacts:
      - "*.apk"