workflows:
  android-apk:
    name: Android APK Build

    environment:
      node: latest

    scripts:
      - npm install
      - npx expo export

    artifacts:
      - dist/**

    publishing:
      email:
        recipients:
          - your@email.com